version: '3'
services:
  postgres:
    container_name: postgres
    image: 'postgres:16-bullseye'
    command: ['postgres', '-c', 'log_statement=all']
    ports:
      - '5432:5432'
    env_file:
      - .env
